language: python
sudo: false

python:
  - 3.6

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run pytest --cov=logme --cov-report=xml -p no:warnings


after_success:
  - codecov